name = "AutomaticDocstrings"
uuid = "70b36510-7dee-11e9-28d4-77afe9445f67"
authors = ["Fredrik Bagge Carlson <baggepinnen@gmail.com>"]
version = "1.0.0"

[deps]
CSTParser = "00ebfdb7-1f24-5e51-bd34-a7502290713f"

[compat]
julia = "1.0"
CSTParser = "<2.3.1" # 2.3.1 removes get_args function and in 2.2.0 the output is a bit messed up

[extras]
DeepDiffs = "ab62b9b5-e342-54a8-a765-a90f495de1a6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"


[targets]
test = ["DeepDiffs", "Test"]
